FROM ubuntu:latest as release

RUN wget -qO- https://deb.nodesource.com/setup_16.x | sudo -E bash - \
    sudo apt install -y nodejs

WORKDIR /App
COPY build ./
EXPOSE 80
CMD NODE_ENV=production npx pm2-runtime index.js --name audiosetAPI